# Generated by Django 3.0.8 on 2020-07-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20200727_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('planets', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('producers', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Personaje',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='personajes',
            field=models.ManyToManyField(related_name='personajes', to='ingredients.Personaje'),
        ),
    ]
