# Generated by Django 3.0.8 on 2020-07-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20200727_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='personajes',
            field=models.ManyToManyField(related_name='peliculas', to='ingredients.Personaje'),
        ),
    ]
